#!/usr/bin/env bash


# set default classpath
if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${CLARA_HOME}/plugins/clas12/lib/services/*"
    export CLASSPATH
fi

java_wrapper=${CLARA_HOME}/lib/clara/run-java

exec "${java_wrapper}" org.jlab.clara.clas12.dc.monitor.DCRingListener "$@"
